Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  # не проверять репозиторий на наличие обновлений 
  config.vm.box_check_update = false 
  
config.vm.network "forwarded_port", guest: 5000, host: 6000
config.vm.network "forwarded_port", guest: 5002, host: 6001



  # отменить создание ssh-ключа 
  config.ssh.insert_key = false 

  config.vm.provider "virtualbox" do |vb| 
    vb.name = "ubuntu-test" 
    vb.memory = 2048 
    vb.cpus = 1 
  end 

 config.vm.hostname = "ubuntu-test" 

 # config.vm.provision "shell", inline: "wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb" 
 # config.vm.provision "shell", inline: "sudo dpkg -i packages-microsoft-prod.deb" 
 # config.vm.provision "shell", inline: "rm packages-microsoft-prod.deb" 

 # config.vm.provision "shell", inline: "sudo apt-get update" 
 # config.vm.provision "shell", inline: "sudo apt-get install -y apt-transport-https" 
 # config.vm.provision "shell", inline: "sudo apt-get update" 
 # config.vm.provision "shell", inline: "sudo apt-get install -y dotnet-sdk-5.0" 

 # config.vm.provision "shell", inline: "dotnet nuget add source --name iivanenko http://10.0.2.2:5000/baget/v3/index.json"
 # config.vm.provision "shell", inline: "sudo dotnet tool install CrossPlatform-lab4 --tool-path /usr/local/lab4/" 
 #config.vm.provision "shell", inline: "sudo dotnet tool update CrossPlatform-lab4 --tool-path /usr/local/lab4/ --no-cache" 
 #config.vm.provision "shell", inline: "sudo ln -sf /usr/local/lab4/iivanenko /usr/local/bin/iivanenko"

 #config.vm.provision "file", source: "../publish/", destination: "usr/app"

  
 #config.vm.provision "shell", inline: "sudo dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM"
 #config.vm.provision "shell", inline: "sudo update-ca-certificates"

 config.vm.provision "shell", inline: "sudo chmod +x usr/app"
 config.vm.provision "shell", path: "startup.sh"
end
